SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, CATEGORY, SUM((SALES) * PRICE) AS 'TOTAL_SALES'
FROM BOOK JOIN (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') AS BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;