SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS 'TOTAL_SALES'
FROM BOOK JOIN (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') AS BOOK_SALES  ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID 
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID

GROUP BY AUTHOR_ID, CATEGORY 
ORDER BY AUTHOR_ID, CATEGORY DESC;