WITH FIRST AS (SELECT ID 
              FROM ECOLI_DATA 
              WHERE PARENT_ID IS NULL),
SECOND AS (SELECT ECOLI_DATA.ID
          FROM FIRST JOIN ECOLI_DATA ON ECOLI_DATA.PARENT_ID = FIRST.ID)
SELECT ECOLI_DATA.ID 
FROM ECOLI_DATA JOIN SECOND ON ECOLI_DATA.PARENT_ID = SECOND.ID
ORDER BY ID;