WITH FIRST_GEN AS (SELECT ECOLI_DATA.ID 
                  FROM ECOLI_DATA 
                  WHERE PARENT_ID IS NULL),
SECOND_GEN AS (SELECT ECOLI_DATA.ID
              FROM ECOLI_DATA JOIN FIRST_GEN ON ECOLI_DATA.PARENT_ID = FIRST_GEN.ID)
SELECT ECOLI_DATA.ID 
FROM SECOND_GEN JOIN ECOLI_DATA ON SECOND_GEN.ID = ECOLI_DATA.PARENT_ID
ORDER BY ID;