WITH VALUE AS (SELECT COUNT(ID) AS 'CHILD', PARENT_ID
              FROM ECOLI_DATA
              WHERE PARENT_ID IS NOT NULL
              GROUP BY PARENT_ID)
SELECT ECOLI_DATA.ID, COALESCE(CHILD, 0) AS 'CHILD_COUNT'
FROM ECOLI_DATA LEFT JOIN VALUE ON ECOLI_DATA.ID = VALUE.PARENT_ID
ORDER BY ID;
