-- 코드를 작성해주세요
WITH VALUE AS (SELECT PARENT_ID, COUNT(ID) AS COUNT
              FROM ECOLI_DATA
              GROUP BY PARENT_ID)
SELECT ID, COALESCE(COUNT, 0) AS CHILD_COUNT 
FROM ECOLI_DATA LEFT JOIN VALUE 
ON ECOLI_DATA.ID = VALUE.PARENT_ID 
ORDER BY ID;
