SELECT RENTAL.CAR_ID, RENTAL.CAR_TYPE, 
ROUND(RENTAL.DAILY_FEE * 30 * (100 - DISCOUNT_RATE)/100)
AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS RENTAL

JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY 
ON RENTAL.CAR_ID = HISTORY.CAR_ID

JOIN (SELECT * 
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
     WHERE DURATION_TYPE LIKE '30%') AS PLAN
ON RENTAL.CAR_TYPE = PLAN.CAR_TYPE

WHERE HISTORY.CAR_ID NOT IN (SELECT CAR_ID 
                             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                             WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
)
GROUP BY RENTAL.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000 AND RENTAL.CAR_TYPE IN ('SUV', '세단')
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;