-- 코드를 작성해주세요
SELECT ID, (CASE WHEN COLONY_LEVEL = 1 THEN 'CRITICAL'
            WHEN COLONY_LEVEL = 2 THEN 'HIGH'
            WHEN COLONY_LEVEL = 3 THEN 'MEDIUM'
            ELSE 'LOW'
            END ) AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS COLONY_LEVEL
     FROM ECOLI_DATA) AS D
     ORDER BY ID;
