SELECT ECOLI.ID, CASE 
WHEN ECOLI.R >= 0.75 THEN 'CRITICAL'
WHEN ECOLI.R >= 0.5 THEN 'HIGH'
WHEN ECOLI.R >= 0.25 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME 
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS R FROM ECOLI_DATA) AS ECOLI
ORDER BY ECOLI.ID;