SELECT DISTINCT USER_ID, NICKNAME,CONCAT(CITY," ", STREET_ADDRESS1," ", STREET_ADDRESS2) '전체주소', CONCAT(SUBSTRING(TLNO, 1, 3), '-',SUBSTRING(TLNO, 4,4), '-', SUBSTRING(TLNO, 8,4)) AS '전화번호'
FROM USED_GOODS_BOARD AS BOARD JOIN USED_GOODS_USER AS USER 
ON BOARD.WRITER_ID = USER.USER_ID
WHERE WRITER_ID IN (SELECT WRITER_ID 
                   FROM USED_GOODS_BOARD
                   GROUP BY WRITER_ID
                   HAVING COUNT(BOARD_ID) >= 3)
ORDER BY USER_ID DESC;