-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as INFO JOIN REST_REVIEW as REVIEW 
ON INFO.REST_ID = REVIEW.REST_ID
GROUP BY INFO.REST_ID
HAVING INFO.ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;