SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', 
COUNT(DISTINCT ONLINE_SALE.USER_ID) AS 'PURCHASED_USERS',
ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS 'PUCHASED_RATIO'
FROM (SELECT * FROM USER_INFO WHERE JOINED LIKE '2021%') AS USER_INFO JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;