SELECT USER_ID, NICKNAME, SUM(PRICE) AS 'TOTAL_SALES'
FROM (SELECT *
     FROM USED_GOODS_BOARD
     WHERE STATUS = 'DONE')
AS BOARD JOIN USED_GOODS_USER AS USER 
ON BOARD.WRITER_ID = USER.USER_ID
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000 
ORDER BY TOTAL_SALES;

# 완료 -> 70 만원 이상 