SELECT HR_EMPLOYEES.EMP_NO, HR_EMPLOYEES.EMP_NAME, 
CASE WHEN AVG(SCORE) < 80 THEN 'C'
WHEN AVG(SCORE) < 90 THEN 'B' 
WHEN AVG(SCORE) < 96 THEN 'A'
ELSE 'S'
END AS GRADE, 
CASE WHEN AVG(SCORE) < 80 THEN 0
WHEN AVG(SCORE) < 90 THEN SAL * 0.1
WHEN AVG(SCORE) < 96 THEN SAL * 0.15
ELSE SAL*0.2
END AS BONUS 
FROM HR_EMPLOYEES JOIN HR_GRADE ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO 
JOIN HR_DEPARTMENT ON HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID
GROUP BY HR_EMPLOYEES.EMP_NO
ORDER BY EMP_NO;