WITH VALUE AS (SELECT MEMBER_ID
              FROM REST_REVIEW 
             GROUP BY MEMBER_ID 
              ORDER BY COUNT(REVIEW_ID) DESC
              LIMIT 1)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE JOIN REST_REVIEW ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID 
WHERE REST_REVIEW.MEMBER_ID IN (SELECT MEMBER_ID 
                               FROM VALUE)
ORDER BY REVIEW_DATE, REVIEW_TEXT;


# 리뷰 가장 많이 회원 -> 리뷰들 조회 