-- 코드를 입력하세요
SELECT PRO.MEMBER_NAME, REVIEW.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE 
FROM MEMBER_PROFILE AS PRO JOIN REST_REVIEW AS REVIEW ON PRO.MEMBER_ID = REVIEW.MEMBER_ID
WHERE PRO.MEMBER_ID = (SELECT MEMBER_ID
                  FROM REST_REVIEW
                  GROUP BY MEMBER_ID
                  ORDER BY COUNT(*) DESC
                  LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;