-- 코드를 작성해주세요
SELECT TREE.ITEM_ID, ITEM_NAME, RARITY 
FROM ITEM_INFO as INFO JOIN ITEM_TREE as TREE 
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID in (SELECT ITEM_ID
                             FROM ITEM_INFO
                             WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;
