-- 코드를 작성해주세요
SELECT ET1.ID, ET1.GENOTYPE, ET2.GENOTYPE AS 'PARENT_GENOTYPE'
FROM ECOLI_DATA AS ET1 JOIN ECOLI_DATA AS ET2 ON ET2.ID = ET1.PARENT_ID
WHERE ET1.GENOTYPE & ET2.GENOTYPE = ET2.GENOTYPE
ORDER BY ID;
