WITH VALUE AS (SELECT CAR_ID 
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
              WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
              GROUP BY CAR_ID 
              HAVING COUNT(HISTORY_ID) >= 5)
SELECT MONTH(START_DATE) AS 'MONTH', VALUE.CAR_ID, COUNT(HISTORY_ID) AS 'RECORDS' 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY JOIN VALUE 
ON VALUE.CAR_ID = HISTORY.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH, CAR_ID DESC;

