WITH VALUE AS (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
              WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
              GROUP BY CAR_ID
              HAVING COUNT(HISTORY_ID) >= 5 )
SELECT MONTH(START_DATE) AS 'MONTH', HISTORY.CAR_ID, COUNT(HISTORY_ID) AS 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY JOIN VALUE
ON HISTORY.CAR_ID = VALUE.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID, MONTH
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH, CAR_ID DESC;
# 총 대여 횟수 5회 이상 
# 대여 횟수가 0인 경우 제외 