WITH VALUE AS (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS 'MAXSIZE'
               FROM ECOLI_DATA
               GROUP BY YEAR)
SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAXSIZE - SIZE_OF_COLONY AS 'YEAR_DEV', ID
FROM ECOLI_DATA JOIN VALUE 
ON VALUE.YEAR = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;