WITH VALUE AS (SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS MAX_SIZE
              FROM ECOLI_DATA
              GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX_SIZE - SIZE_OF_COLONY AS 'YEAR_DEV', ID
FROM VALUE JOIN ECOLI_DATA ON VALUE.YEAR = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;