WITH VALUE AS (SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
              FROM ECOLI_DATA
              GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAXSIZE - SIZE_OF_COLONY AS 'YEAR_DEV', ID
FROM ECOLI_DATA JOIN VALUE ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = VALUE.YEAR
ORDER BY YEAR, YEAR_DEV;