-- 코드를 입력하세요
SELECT SALE.FLAVOR
FROM FIRST_HALF as SALE JOIN ICECREAM_INFO as INFO 
ON SALE.FLAVOR = INFO.FLAVOR
WHERE INFO.INGREDIENT_TYPE like 'fruit%' and SALE.TOTAL_ORDER > 3000
ORDER BY SALE.TOTAL_ORDER DESC;