SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS INFO JOIN FISH_NAME_INFO AS NAME 
ON INFO.FISH_TYPE = NAME.FISH_TYPE 
WHERE (INFO.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                             FROM FISH_INFO 
                             GROUP BY FISH_TYPE)
ORDER BY ID;