# -- 코드를 작성해주세요
WITH VALUE AS (SELECT 
               CASE WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') > 0 
        and SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0 THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0 THEN 'B'
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') > 0 THEN 'C'
END AS 'GRADE', ID
FROM DEVELOPERS)

SELECT GRADE, VALUE.ID, EMAIL
FROM VALUE JOIN DEVELOPERS ON VALUE.ID = DEVELOPERS.ID
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;

 
