WITH VALUE AS 
(SELECT CASE WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') > 0 AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B' 
WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') THEN 'C'
END AS 'GRADE', ID
FROM DEVELOPERS)

SELECT GRADE, DEVELOPERS.ID, EMAIL
FROM DEVELOPERS JOIN VALUE ON DEVELOPERS.ID = VALUE.ID
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;